version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "5000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true

  # volumes:
  #   - ./myblog:/app
  #   - /app/node_modules
